"""Initial migration.

Revision ID: 29fe0a12099c
Revises: 
Create Date: 2021-11-09 18:28:57.518308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29fe0a12099c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movies')
    op.drop_table('review')
    op.add_column('post', sa.Column('course', sa.String(length=100), nullable=False))
    op.add_column('post', sa.Column('teacher_name', sa.String(length=100), nullable=False))
    op.add_column('post', sa.Column('time', sa.String(length=30), nullable=False))
    op.drop_column('post', 'name')
    op.drop_column('post', 'image_file')
    op.drop_column('post', 'content')
    op.drop_column('post', 'qty')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('qty', sa.INTEGER(), nullable=False))
    op.add_column('post', sa.Column('content', sa.TEXT(), nullable=False))
    op.add_column('post', sa.Column('image_file', sa.VARCHAR(length=20), nullable=False))
    op.add_column('post', sa.Column('name', sa.VARCHAR(length=100), nullable=False))
    op.drop_column('post', 'time')
    op.drop_column('post', 'teacher_name')
    op.drop_column('post', 'course')
    op.create_table('review',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('review', sa.VARCHAR(length=100), nullable=False),
    sa.Column('post_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('movies',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('poster', sa.VARCHAR(length=20), nullable=True),
    sa.Column('poster_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['poster_id'], ['post.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
